import Head from 'next/head'
import Header from "../components/Header"
import Sidebar from "../components/Sidebar"
import Feed from '../components/Feed'
import Widgets from '../components/Widgets'

export default function Home() {
  return (
    <div className="scrollbar invisible-scrollbar">
      <Head>
        <title>Fb Clone</title>
        <meta name="Fb clone" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />  

      <main className="flex bg-gray-100 scrollbar-thin">
        <Sidebar />
        <Feed />
        <Widgets />
      </main>
    </div>
  )
}