// import {getSession} from "next-auth/client"
import Head from 'next/head'
import Header from "../components/Header"
// import Login from "../components/Login"
import Sidebar from "../components/Sidebar"
import Feed from '../components/Feed'
import Widgets from '../components/Widgets'
import { db } from '../firebase'

export default function Home({posts}) {
  // if (!session) return <Login />

  return (
    <div className="scrollbar invisible-scrollbar h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Fb Clone</title>
        <meta name="Fb clone" content="Generated by create next app" />
      </Head>

      <Header />  

      <main className="flex scrollbar-thin ">
        <Sidebar />
        <Feed posts={posts}/>
        <Widgets />
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  // const session = await getSession(context)

  const posts = await db.collection("posts").orderBy("timestamp", "desc").get()

  const docs = posts.docs.map((post) => ({
    id: post.id,
    ...post.data(),
    timestamp: null,
  }))

  return {
    props: {
      // session,
      posts: docs,
    },
  }
}